version: '3.9'

services:
  api:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: fastapi-filmes
    ports:
      - "8000:8000"
    volumes:
      - ./server:/app
    restart: always