version: '3.9'

services:
  api:
    container_name: fastapi-filmes
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./server:/app
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
